### ISSUE TITLE
Can’t find files if working directory isn’t the root folder

### ISSUE THREAD

**Issue by arm32x** [vagnum08/2048-gtk#1]
When I run the launch script with a current working directory other than where I put the root of this repository in my filesystem, it can’t find the files `pyweb.py` and `mywebserver.py`. However, it found these files just fine when I changed my working directory to the repository root and then ran the script. Could you please fix this so that it doesn’t require the working directory to be the repository root?

**Comment by vagnum08** [comment]
OK. I will have look in the next days. I have an idea on how to fix this.

**Comment by vagnum08** [comment]
Hi, I have updated and merged the code. 

If you use `pip --user install .` you will be able to launch it from the terminal in any directory. However, if you install it with `sudo pip install .` you will get a desktop entry as well.

If you have any problems, let me know.
